{% set name = "apply_defaults" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fd246314cb4bd90a6f2c4e07f6812d2dc6c85829119e591d8d8adc0993fa3cc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - apply_defaults

about:
  home: https://github.com/bcb/apply_defaults
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Helps pull configuration into a project.
  dev_url: https://github.com/bcb/apply_defaults

extra:
  recipe-maintainers:
    - bcb
