{% set name = "apply_defaults" %}
{% set version = "0.1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ce26326a61d8773d38a9726a345c6525a91a6120d7333af79ad792dacb6246c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - apply_defaults

about:
  home: https://github.com/bcb/apply_defaults
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Helps pull configuration into a project.
  dev_url: https://github.com/bcb/apply_defaults

extra:
  recipe-maintainers:
    - bcb
