travis:
  secure:
    BINSTAR_TOKEN: L6aaMfxKfwaXP8xY9x/Q9HmbZRCf/IOZQildHMH+Y2RLKySBS2NdOSJ3nm3nZEZxVvET2sBUjNb/PrCAl7ZzZE+l45aM/CH6rHNbwESaU64KU/d0SJDt4FmxrV3VApdIol7BO1ULQe3FcmrnmiU0P8DPMybvXDXiV0RCDe5qAOx8iuExsg515L1GlgS1E1yi280P8hb4gPwEYnqkRw0SMsmrTVpn1HPiX7tylEXYoHof7Ux0GsMahxkrZkJDuNuvJEE0Jml2QJGROp9aNpE9gDNprxwN9aZAuEPY/9p/2+8c0XhTbh9pXc7DKoSP/CtcfIu2BgfO/JiY+GtgzBXYrT78HYF3nOZ/HLhtxP2WsCDCh6i+VgMV6Ot4Bf2mPKtzbDGoPQEpmuiXLuVT4kMucnUuvl8JY9LNsOQ5ojjM8KZKe+XfsLWF8OPkLFYXZSnCRlKxIljrpVC2VJDrbwrCzq5eFG5dGhsU7jlqktSU/uqsuAkKWbSMiQBEdUSiCJJcGiwpqYOChNSGxYwI7S18a07j33amT1IMUapXEKM5h98pbaQHJob9xkOrlLjX4L7EWi/JP0J/Glgn/P2b60PSHI8v07gSoxTRUUTRqEyOhOig1pRN4VPNwOCgXIi1tq2mrYV0TJHmJc6JTN/1X/dqYwz3x27xYXjrfz8x0KfiayE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
